version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: psql14
    environment:
      - POSTGRES_PASSWORD=4144
      - POSTGRES_DB=todolistsdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "414424"
    ports:
      - '8080:80' 
    volumes:
      - pgadmin:/var/lib/pgadmin

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025


  web:
    container_name: todolist-app
    build: ./
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4144
      POSTGRES_HOST: psql14
      POSTGRES_DB: todolistsdb
      NEXT_PUBLIC_APP_API: http://127.0.0.1:3000/api
      NEXT_PUBLIC_APP_APIIN: http://localhost:3000/api
      # DATABASE_URL: postgres://postgres:4144d@psql14:5432/todolistsdb

volumes:
  db_data:
  pgadmin: