version: '3.8'

services:
  # cypress:
  #   image: "cypress/included:12.3.0"
  #   entrypoint: cypress
  #   container_name: cypress
  #   working_dir: /e2e
  #   volumes:
  #     - ./:/e2e
  cypress:
    image: "cypress/included:12.3.0"
    container_name: cypress

    environment:
      - CYPRESS_baseUrl=http://localhost:3000

    # command: npx cypress run --browser chrome
    working_dir: /e2e
    volumes:
      - ./:/e2e
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js


   


