version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=414424
      - POSTGRES_DB= todolists
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - pgsite

  pgadmin-compose:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "414424"
    ports:
      - '8080:80' 
    networks:
      - pgsite
networks:
  pgsite:
volumes:
  db_data:
