version: '3.8'

services:
  # cypress:
  #   image: "cypress/included:12.3.0"
  #   entrypoint: cypress
  #   container_name: cypress
  #   working_dir: /e2e
  #   volumes:
  #     - ./:/e2e
   e2e-chrome:
    image: "cypress/included:12.3.0"
    container_name: cypress
   
    command: npx cypress run --browser chrome
    
   
    volumes:
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js


   


