version: '3.9'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = 4144  
    ports:
      -"5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"
  app:
    container_name: demo_todolist:v1
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "3001:3000"
    depends_on:
        - postgres
volumes:
  data: