/// <reference types="cypress" />
describe('Test login verify and permistion User', () => {
  // beforeEach(() => {
  //   cy.visit('/')
  //   cy.wait(2000)
  // })
  
  it('No login permistion', () => {
    cy.visit('/')
    // cy.wait(2000)
    cy.wait(3000)
    cy.visit('/user/Userdashboard/3')
    cy.wait(5000)
    cy.visit('/admin/Admindashboard')
    cy.wait(5000)
  
  })
  it('Verify Test', () => {
    cy.visit('/')
    // cy.wait(2000)
    cy.get('#mobile-menu').click({ force: true })
    cy.wait(1000)
    cy.get('#Login-header').click()
    cy.get('#Login-Input_Email').click().type('sarun4146@gmail.com')
    cy.wait(1000)
    cy.get('#Login-Input_Password').click().type('kokai414424')
    cy.wait(2000)
    cy.get('#Login-Submit').click()
    cy.wait(4000)
    cy.get('button').contains('ตกลง').type('{enter}')
    cy.log("USER IS NOT VERIFY")
    cy.wait(3000)
    cy.get('#Login-Input_Email').click().clear().type('sarun4144@gmail.com')
    cy.wait(1000)
    cy.get('#Login-Input_Password').click().clear().type('kokai414424')
    cy.wait(2000)
    cy.get('#Login-Submit').click()
    cy.wait(2000)
    cy.get('#user-dashboard').click()
    cy.wait(5000)
  
  })



  it('user go to admin path Test', () => {
    cy.visit('/')
    cy.wait(2000)
    cy.get('#mobile-menu').click({ force: true })
    cy.wait(1000)
    cy.get('#Login-header').click()
    cy.wait(1000)
    cy.get('#Login-Input_Email').click().clear().type('sarun4144@gmail.com')
    cy.wait(1000)
    cy.get('#Login-Input_Password').click().clear().type('kokai414424')
    cy.wait(2000)
    cy.get('#Login-Submit').click()
    cy.wait(2000)
    cy.get('#user-dashboard').click()
    cy.wait(5000)
    cy.visit('/admin/Admindashboard')
    cy.wait(5000)
    cy.get('#user-dashboard').click()
  })
  // it('User-Login-visit-Dashboard', () => {
  //   cy.get('#mobile-menu').click({force:true})
  //   cy.wait(1000)
  //   cy.get('#Login-header').click()
  //   cy.get('#Login-Input_Email').click().type('sarun4144@gmail.com')
  //   cy.wait(1000)
  //   cy.get('#Login-Input_Password').click().type('kokai414424')
  //   cy.wait(1000)
  //   cy.get('#Login-Submit').click() 
  //   cy.wait(4000)
  //   cy.get('#user-dashboard').click()
  //   cy.wait(2000)
  //   cy.get('#userdashboard-add-btn').click()
  //   cy.wait(1000)
  //   cy.get('#todolistadd-todolistname-input').click().type('Test todolist')
  //   cy.get('#todolistdd-list-btn').click()
  //   cy.get('#todolistdd-list-btn').click()
  //   cy.wait(1000)
  //   cy.get('#todolistadd-addinput-1').click().type('Test list 1')
  //   cy.get('#todolistadd-addinput-2').click().type('Test list 2')
  //   cy.get('#todolistadd-addinput-3').click().type('Test list 3')
  //   cy.wait(1000)
  //   cy.get('#todolistadd-deleteinput-2').click()
  //   cy.wait(500)
  //   cy.get('#todolistadd-addinput-2').click().clear().type('Test list 3 to 2')
  //   cy.get('#todolistdd-list-btn').click()
  //   cy.wait(500)
  //   cy.get('#todolistadd-addinput-3').click().type('The new test list 3')
  //   cy.wait(200)
  //   cy.get('#todolistadd-date').type('2030-01-19')
  //   cy.wait(500)
  //   cy.get('select').select(5)
  //   cy.wait(500)
  //   cy.get('#todolistadd-confirm-btn').click()
  //   cy.wait(1000)
  //   cy.get('#Logout-header').click()
  // })

  // it('User-Dashboard-list And Do list', () => {
  //   cy.get('#mobile-menu').click({force:true})
  //   cy.wait(1000)
  //   cy.get('#Login-header').click()
  //   cy.get('#Login-Input_Email').click().type('sarun4144@gmail.com')
  //   cy.wait(1000)
  //   cy.get('#Login-Input_Password').click().type('kokai414424')
  //   cy.wait(2000)
  //   cy.get('#Login-Submit').click() 
  //   cy.wait(4000)
  //   cy.get('#user-dashboard').click()
  //   cy.wait(5000)
  //   cy.get('#dropdown-cat').click()
  //   // cy.get('button').invoke('attr','name').contains('Sport').click()
  //   // cy.wait(1000)
  //  cy.get('#category-1').click()
  //  cy.wait(1000)
  //  cy.get('#dropdown-cat').click()
  //  cy.get('#category-2').click()
  //  cy.wait(1000)
  //  cy.get('#dropdown-cat').click()
  //  cy.get('#category-3').click()
  //  cy.wait(1000)
  //  cy.get('#dropdown-cat').click()
  //  cy.get('#category-4').click()
  //  cy.wait(1000)
  //  cy.get('#dropdown-cat').click()
  //  cy.get('#category-5').click()
  //  cy.wait(1000)
  //  cy.get('#dropdown-cat').click()
  //  cy.get('#Category-ALL').click()
  //  cy.wait(1000)
  //  cy.get('#dropdown-status').click()
  //  cy.get('#P').click()
  //  cy.wait(1000)
  //  cy.get('#dropdown-status').click()
  //  cy.get('#S').click()
  //  cy.wait(1000)
  //  cy.get('#dropdown-status').click()
  //  cy.get('#status-ALL').click()
  //  cy.wait(1000)
  //  cy.get('#listname5').click()
  //  cy.wait(1000)
  //  cy.get('#checkbox-1').click()
  //  cy.wait(1000)
  //  cy.get('#checkbox-3').click()
  //  cy.wait(1000)
  //  cy.get('#checkbox-2').click()
  //  cy.wait(1000)
  //  cy.get('#checkbox-3').click()
  //  cy.wait(1000)
  //  cy.get('#checkbox-1').click()
  //  cy.wait(1000)
  //  cy.get('#checkbox-1').click()
  //  cy.wait(1000)
  //  cy.get('#checkbox-3').click()
  //  cy.wait(1000)
  //  cy.get('#listsubmit-Submit').click()
  //  cy.get(1000)
  //  cy.get('#user-dashboard').click()
  // })
})